on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Mvn
        run: ./mvnw clean package
      - name: Build image
        run: docker build -t slisnychyi/scrape2 .
      - name: Image run
        if: github.ref != 'refs/heads/master'
        run: docker run scrape2
      - name: Image push
        if: github.ref == 'refs/heads/master'
        run: docker push slisnychyi/scrape2
