on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Mvn
        run: ./mvnw clean package
      - name: Build image
        run: docker build -t scrape2 .
      - name: Image run
        run: docker run scrape2